project:
  version: 0.0.1-SNAPSHOT
  applicationName: CargoTrackingBackend

jwt:
  accessTokenSecret: 1234
  accessTokenLifeTime: 360000

  refreshTokenSecret: 1234
  refreshTokenLifeTime: 120000

server:
  port: 8080

spring:
  application:
    name: web
  datasource:
    url: jdbc:postgresql://localhost:5432/trucking
    username: postgres
    password: shushkevich

service:
  user-core-url: http://localhost:8081