project:
  version: 0.0.1-SNAPSHOT
  applicationName: CargoTrackingBackend

server:
  port: 8080

spring:
  application:
    name: web
  datasource:
    url: jdbc:postgresql://localhost:5432/trucking
    username: postgres
    password: shushkevich

service:
  user-core-url: http://localhost:8081