project:
  version: 0.0.1-SNAPSHOT
  applicationName: CargoTrackingBackend

jwt:
  accessTokenSecret: 1234
  accessTokenLifeTime: 360000000000

  refreshTokenSecret: 1234
  refreshTokenLifeTime: 1200000

server:
  port: 8080

spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

service:
  user-core-url: http://localhost:8081