server:
  port: ${CORE_SERVER_PORT}

spring:
  application:
    name: core

  datasource:
    url: jdbc:postgresql://localhost:5432/trucking
    username: ${DB_USER_USERNAME}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect

      format_sql: true

    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug