server:
  port: 8081

spring:
  application:
    name: core

  datasource:
    url: jdbc:postgresql://localhost:5432/trucking
    username: postgres
    password: shushkevich

  jpa:
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

      format_sql: true

    show-sql: true
logging:
  level:
    org.hibernate.SQL: debug